// automatically generated by the FlatBuffers compiler, do not modify

import { flatbuffers } from "./flatbuffers"
/**
 * @enum
 */
export namespace log{
export enum Msg{
  NONE= 0,
  Log= 1,
  LogConfig= 2
}};

/**
 * @constructor
 */
export namespace log{
export class Log {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Log
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Log {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Log= obj
 * @returns Log
 */
static getRootAsLog(bb:flatbuffers.ByteBuffer, obj?:Log):Log {
  return (obj || new Log).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns flatbuffers.Long
 */
time():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @returns number
 */
level():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns flatbuffers.Long
 */
filter():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @returns flatbuffers.Long
 */
object():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
function():string|null
function(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
function(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns number
 */
line():number {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns flatbuffers.Long
 */
thread():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
msg():string|null
msg(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
msg(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startLog(builder:flatbuffers.Builder) {
  builder.startObject(8);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long time
 */
static addTime(builder:flatbuffers.Builder, time:flatbuffers.Long) {
  builder.addFieldInt64(0, time, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param number level
 */
static addLevel(builder:flatbuffers.Builder, level:number) {
  builder.addFieldInt8(1, level, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long filter
 */
static addFilter(builder:flatbuffers.Builder, filter:flatbuffers.Long) {
  builder.addFieldInt64(2, filter, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long object
 */
static addObject(builder:flatbuffers.Builder, object:flatbuffers.Long) {
  builder.addFieldInt64(3, object, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset functionOffset
 */
static addFunction(builder:flatbuffers.Builder, functionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, functionOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number line
 */
static addLine(builder:flatbuffers.Builder, line:number) {
  builder.addFieldInt32(5, line, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long thread
 */
static addThread(builder:flatbuffers.Builder, thread:flatbuffers.Long) {
  builder.addFieldInt64(6, thread, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset msgOffset
 */
static addMsg(builder:flatbuffers.Builder, msgOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, msgOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endLog(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace log{
export class LogConfig {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns LogConfig
 */
__init(i:number, bb:flatbuffers.ByteBuffer):LogConfig {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param LogConfig= obj
 * @returns LogConfig
 */
static getRootAsLogConfig(bb:flatbuffers.ByteBuffer, obj?:LogConfig):LogConfig {
  return (obj || new LogConfig).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
level():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns flatbuffers.Long
 */
filter():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @returns flatbuffers.Long
 */
object():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
function():string|null
function(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
function(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns number
 */
line():number {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns flatbuffers.Long
 */
thread():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
regexp():string|null
regexp(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
regexp(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startLogConfig(builder:flatbuffers.Builder) {
  builder.startObject(7);
};

/**
 * @param flatbuffers.Builder builder
 * @param number level
 */
static addLevel(builder:flatbuffers.Builder, level:number) {
  builder.addFieldInt8(0, level, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long filter
 */
static addFilter(builder:flatbuffers.Builder, filter:flatbuffers.Long) {
  builder.addFieldInt64(1, filter, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long object
 */
static addObject(builder:flatbuffers.Builder, object:flatbuffers.Long) {
  builder.addFieldInt64(2, object, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset functionOffset
 */
static addFunction(builder:flatbuffers.Builder, functionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, functionOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number line
 */
static addLine(builder:flatbuffers.Builder, line:number) {
  builder.addFieldInt32(4, line, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long thread
 */
static addThread(builder:flatbuffers.Builder, thread:flatbuffers.Long) {
  builder.addFieldInt64(5, thread, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset regexpOffset
 */
static addRegexp(builder:flatbuffers.Builder, regexpOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, regexpOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endLogConfig(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace log{
export class Buffer {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Buffer
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Buffer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Buffer= obj
 * @returns Buffer
 */
static getRootAsBuffer(bb:flatbuffers.ByteBuffer, obj?:Buffer):Buffer {
  return (obj || new Buffer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns log.Msg
 */
msgType():log.Msg {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : log.Msg.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
msg<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startBuffer(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param log.Msg msgType
 */
static addMsgType(builder:flatbuffers.Builder, msgType:log.Msg) {
  builder.addFieldInt8(0, msgType, log.Msg.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset msgOffset
 */
static addMsg(builder:flatbuffers.Builder, msgOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, msgOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endBuffer(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishBufferBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

}
}
